### ISSUE TITLE
NativeJS code review

### ISSUE THREAD

**Issue by sninala** [chmkreddy/selflearning#1]
1. please organize all the js files into multiple folders like HW1, HW2 HW3. 
2. Indent the code properly in WordCount.js, FunctionWithinFunction.js, CalculatingWithFunctions.js, GetMiddle.js, UsingClosuresShareClassState.js .. etc. Please review your code indentation once again.
3. Mutiple return statements in single function is a bad practice. the getMiddle function in GetMiddle.js has mutlple return statements. Assign it to a result variable and return it. 
4. name == undefined && weight == undefined . This condition will fail if I pass null or 0 to name and weight. rewrite this to if(!name && !weight) which will check for all false values.

**Comment by sninala** [comment]
@chmkreddy , please address the above comments ..

**Comment by chmkreddy** [comment]
Implemented the code review comments.
